version: '3.8'

services:
  # database:
  #   image: mongo
  #   container_name: phone-book-db
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - dbdata:/data/db
  #   networks:
  #     - phone-book-network
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password


  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: phone-book-server
    # depends_on:
    #   - database
    container_name: phone-book-server
    environment:
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_HOST: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: MONGO_PHONE_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      # ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    ports:
      - "4000:4000"
    volumes:
      - dbdata:/server
      - .:/server
    networks:
      - phone-book-network

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    image: phone-book-client
    depends_on:
      - server
    stdin_open: true
    container_name: phone-book-client
    ports:
      - "3000:3000"
    networks:
      - phone-book-network

networks:
  phone-book-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
