version: '3'

services:
  database:
    image: mongo
    container_name: phone-book-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:  
      - dbdata:/data/db   
    networks:
      - phone-book-network 
  server:
    image: phone-book-server
    depends_on:
      - database
    container_name: phone-book-server
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    ports:
      - "4000:4000"
    volumes:
      - dbdata:/data/db
    networks:
      - phone-book-network
  client:
    image: phone-book-client
    stdin_open: true
    container_name: phone-book-client
    ports:
      - "3000:3000"
networks:
    phone-book-network:
      driver: bridge
volumes:
  dbdata:
   driver: local



